package com.boaat.jazzy_cookin.kitchen;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import com.mojang.serialization.Codec;

import io.netty.buffer.ByteBuf;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.util.StringRepresentable;

public enum IngredientState implements StringRepresentable {
    RAW("raw"),
    WASHED("washed"),
    WHOLE("whole"),
    PEELED("peeled"),
    SLICED("sliced"),
    CHOPPED("chopped"),
    DICED("diced"),
    MINCED("minced"),
    ROUGH_CUT("rough_cut"),
    STRAINED("strained"),
    CRUSHED("crushed"),
    COARSE_PASTE("coarse_paste"),
    SMOOTH_PASTE("smooth_paste"),
    OVERWORKED_PASTE("overworked_paste"),
    COARSE_POWDER("coarse_powder"),
    FINE_POWDER("fine_powder"),
    MIXED("mixed"),
    SMOOTH_MIXTURE("smooth_mixture"),
    LUMPY_MIXTURE("lumpy_mixture"),
    UNDERWHISKED("underwhisked"),
    WHISKED("whisked"),
    OVERWHISKED("overwhisked"),
    SEPARATED("separated"),
    SHAGGY_DOUGH("shaggy_dough"),
    ROUGH_DOUGH("rough_dough"),
    DEVELOPING_DOUGH("developing_dough"),
    DEVELOPED_DOUGH("developed_dough"),
    SMOOTH_DOUGH("smooth_dough"),
    ELASTIC_DOUGH("elastic_dough"),
    OVERWORKED_DOUGH("overworked_dough"),
    BATTERED("battered"),
    MARINATED("marinated"),
    BOILED("boiled"),
    SIMMERED("simmered"),
    PAN_FRIED("pan_fried"),
    DEEP_FRIED("deep_fried"),
    BAKED("baked"),
    ROASTED("roasted"),
    STEAMED("steamed"),
    SMOKED("smoked"),
    FERMENTED("fermented"),
    COOLED("cooled"),
    RESTED("rested"),
    GLAZED("glazed"),
    PLATED("plated"),
    PANTRY_READY("pantry_ready"),
    WHOLE_APPLE("whole_apple"),
    WILD_BERRIES("wild_berries"),
    PEELED_APPLE("peeled_apple"),
    SLICED_APPLE("sliced_apple"),
    WHOLE_TOMATO("whole_tomato"),
    CHOPPED_TOMATO("chopped_tomato"),
    WHOLE_HERB("whole_herb"),
    CHOPPED_HERB("chopped_herb"),
    GROUND_HERB("ground_herb"),
    DRIED_HERB("dried_herb"),
    WHOLE_WHEAT("whole_wheat"),
    WHOLE_CABBAGE("whole_cabbage"),
    CHOPPED_CABBAGE("chopped_cabbage"),
    WHOLE_ONION("whole_onion"),
    DICED_ONION("diced_onion"),
    WHOLE_EGG("whole_egg"),
    FRESH_MILK("fresh_milk"),
    RAW_FISH("raw_fish"),
    CLEANED_FISH("cleaned_fish"),
    RAW_PROTEIN("raw_protein"),
    MARINADE("marinade"),
    BRINE("brine"),
    CANNING_SYRUP("canning_syrup"),
    MARINATED_PROTEIN("marinated_protein"),
    BATTER("batter"),
    BATTERED_PROTEIN("battered_protein"),
    FRIED_PROTEIN("fried_protein"),
    ROAST_CUT("roast_cut"),
    ROASTED_PROTEIN("roasted_protein"),
    BROILED_PROTEIN("broiled_protein"),
    SMOKED_PROTEIN("smoked_protein"),
    WHOLE_SPICE("whole_spice"),
    GROUND_SPICE("ground_spice"),
    CRUST_MIX("crust_mix"),
    DOUGH("dough"),
    BREAD_DOUGH("bread_dough"),
    BAKED_BREAD("baked_bread"),
    RESTED_BREAD("rested_bread"),
    SLICED_BREAD("sliced_bread"),
    SOUP_BASE("soup_base"),
    STRAINED_SOUP("strained_soup"),
    DUMPLING_FILLING("dumpling_filling"),
    DUMPLING_DOUGH("dumpling_dough"),
    RAW_DUMPLINGS("raw_dumplings"),
    STEAMED_DUMPLINGS("steamed_dumplings"),
    PORTIONED_MEAL("portioned_meal"),
    ASSEMBLED_SANDWICH("assembled_sandwich"),
    STICKED_PRODUCT("sticked_product"),
    ROAST_VEGETABLES("roast_vegetables"),
    CANNED_TOMATO("canned_tomato"),
    APPLE_PRESERVE("apple_preserve"),
    DRIED_FRUIT("dried_fruit"),
    FERMENTED_VEGETABLE("fermented_vegetable"),
    CULTURED_DAIRY("cultured_dairy"),
    HOT_PRESERVE("hot_preserve"),
    FRESH_OIL("fresh_oil"),
    USED_OIL("used_oil"),
    DIRTY_OIL("dirty_oil"),
    BURNT_OIL("burnt_oil"),
    SIMMERED_FILLING("simmered_filling"),
    RAW_ASSEMBLED_PIE("raw_assembled_pie"),
    BAKED_PIE("baked_pie"),
    COOLED_PIE("cooled_pie"),
    RESTED_PIE("rested_pie"),
    SLICED_PIE("sliced_pie"),
    PLATED_SLICE("plated_slice"),
    PLATED_SOUP_MEAL("plated_soup_meal"),
    PLATED_DUMPLING_MEAL("plated_dumpling_meal"),
    PLATED_FRIED_MEAL("plated_fried_meal"),
    PLATED_ROAST_MEAL("plated_roast_meal"),
    WHITE_SUGAR("white_sugar"),
    LIGHT_BROWN_SUGAR("light_brown_sugar"),
    DARK_BROWN_SUGAR("dark_brown_sugar"),
    POWDERED_SUGAR("powdered_sugar"),
    HONEY("honey"),
    MAPLE_SYRUP("maple_syrup"),
    MOLASSES("molasses"),
    CORN_SYRUP("corn_syrup"),
    AGAVE_NECTAR("agave_nectar"),
    ALL_PURPOSE_FLOUR("all_purpose_flour"),
    BREAD_FLOUR("bread_flour"),
    CAKE_FLOUR("cake_flour"),
    WHOLE_WHEAT_FLOUR("whole_wheat_flour"),
    CORN_FLOUR("corn_flour"),
    CORNMEAL("cornmeal"),
    WHITE_RICE_FLOUR("white_rice_flour"),
    BROWN_RICE_FLOUR("brown_rice_flour"),
    ROLLED_OATS("rolled_oats"),
    QUICK_OATS("quick_oats"),
    PASTA("pasta"),
    QUINOA("quinoa"),
    SEMOLINA("semolina"),
    BREADCRUMBS("breadcrumbs"),
    BAKING_SODA("baking_soda"),
    BAKING_POWDER("baking_powder"),
    ACTIVE_DRY_YEAST("active_dry_yeast"),
    INSTANT_YEAST("instant_yeast"),
    SOURDOUGH_STARTER("sourdough_starter"),
    CREAM_OF_TARTAR("cream_of_tartar"),
    TABLE_SALT("table_salt"),
    KOSHER_SALT("kosher_salt"),
    SEA_SALT("sea_salt"),
    BLACK_PEPPER("black_pepper"),
    CINNAMON("cinnamon"),
    NUTMEG("nutmeg"),
    PAPRIKA("paprika"),
    CUMIN("cumin"),
    CLOVES("cloves"),
    CHILI_POWDER("chili_powder"),
    GARLIC_POWDER("garlic_powder"),
    ONION_POWDER("onion_powder"),
    BASIL("basil"),
    THYME("thyme"),
    ROSEMARY("rosemary"),
    PARSLEY("parsley"),
    DILL("dill"),
    OREGANO("oregano"),
    MINT("mint"),
    SAGE("sage"),
    VEGETABLE_OIL("vegetable_oil"),
    OLIVE_OIL("olive_oil"),
    CANOLA_OIL("canola_oil"),
    COCONUT_OIL("coconut_oil"),
    BUTTER("butter"),
    SHORTENING("shortening"),
    LARD("lard"),
    POWDERED_MILK("powdered_milk"),
    EVAPORATED_MILK("evaporated_milk"),
    SWEETENED_CONDENSED_MILK("sweetened_condensed_milk"),
    SHELF_STABLE_CREAM("shelf_stable_cream"),
    ALMOND_MILK("almond_milk"),
    OAT_MILK("oat_milk"),
    SOY_MILK("soy_milk"),
    CHEESE("cheese"),
    CHICKEN("chicken"),
    FISH_FILLET("fish_fillet"),
    PORK("pork"),
    BEEF("beef"),
    EGGS("eggs"),
    TOFU("tofu"),
    APPLES("apples"),
    TOMATOES("tomatoes"),
    CARROTS("carrots"),
    ONIONS("onions"),
    POTATOES("potatoes"),
    LEMONS("lemons"),
    CABBAGE("cabbage"),
    GARLIC("garlic"),
    GINGER("ginger"),
    SHALLOTS("shallots"),
    CANNED_TOMATOES("canned_tomatoes"),
    TOMATO_PASTE("tomato_paste"),
    BLACK_BEANS("black_beans"),
    KIDNEY_BEANS("kidney_beans"),
    CHICKPEAS("chickpeas"),
    BROTH("broth"),
    STOCK("stock"),
    COCONUT_MILK("coconut_milk"),
    PEANUT_BUTTER("peanut_butter"),
    JAM("jam"),
    JELLY("jelly"),
    PICKLES("pickles"),
    BRINED_VEGETABLES("brined_vegetables"),
    SYRUP_PRESERVES("syrup_preserves"),
    CHOCOLATE_CHIPS("chocolate_chips"),
    COCOA_POWDER("cocoa_powder"),
    VANILLA_EXTRACT("vanilla_extract"),
    SPRINKLES("sprinkles"),
    CARAMEL_BITS("caramel_bits"),
    ALMONDS("almonds"),
    WALNUTS("walnuts"),
    PECANS("pecans"),
    RAISINS("raisins"),
    DRIED_CRANBERRIES("dried_cranberries"),
    SPAGHETTI("spaghetti"),
    MACARONI("macaroni"),
    RAMEN("ramen"),
    COUSCOUS("couscous"),
    LENTILS("lentils"),
    DRY_BEANS("dry_beans"),
    BREAD("bread"),
    KETCHUP("ketchup"),
    MUSTARD("mustard"),
    MAYONNAISE("mayonnaise"),
    SOY_SAUCE("soy_sauce"),
    WHITE_VINEGAR("white_vinegar"),
    APPLE_CIDER_VINEGAR("apple_cider_vinegar"),
    BALSAMIC_VINEGAR("balsamic_vinegar"),
    HOT_SAUCE("hot_sauce"),
    WORCESTERSHIRE_SAUCE("worcestershire_sauce"),
    TOMATO_SAUCE("tomato_sauce"),
    DRIED_GARLIC("dried_garlic"),
    DRIED_ONIONS("dried_onions"),
    CRACKERS("crackers"),
    COOKIES("cookies"),
    CANDY("candy"),
    CHIPS("chips"),
    ITALIAN_SEASONING("italian_seasoning"),
    CURRY_POWDER("curry_powder"),
    PANCAKE_MIX("pancake_mix"),
    CAKE_MIX("cake_mix"),
    FERMENTATION_STARTER("fermentation_starter"),
    VINEGAR_MOTHER("vinegar_mother"),
    MATCHA("matcha"),
    ROSE_WATER("rose_water"),
    FOOD_COLORING("food_coloring"),
    CHUNKY("chunky"),
    SMOOTH("smooth"),
    CREAMY("creamy"),
    PASTE("paste"),
    MUSH("mush"),
    SEPARATED_BLEND("separated_blend"),
    FRESH_JUICE("fresh_juice"),
    PULP("pulp"),
    BITTER_JUICE("bitter_juice"),
    FREEZE_DRIED("freeze_dried"),
    BRITTLE_WASTE("brittle_waste"),
    SPOILED("spoiled"),
    MOLDY("moldy");

    private static final Map<String, IngredientState> BY_NAME = Arrays.stream(values())
            .collect(Collectors.toMap(IngredientState::getSerializedName, Function.identity()));

    public static final Codec<IngredientState> CODEC = Codec.STRING.xmap(IngredientState::byName, IngredientState::getSerializedName);
    public static final StreamCodec<ByteBuf, IngredientState> STREAM_CODEC = ByteBufCodecs.STRING_UTF8.map(
            IngredientState::byName,
            IngredientState::getSerializedName
    );

    private final String serializedName;

    IngredientState(String serializedName) {
        this.serializedName = serializedName;
    }

    public static IngredientState byName(String name) {
        return BY_NAME.getOrDefault(name, PANTRY_READY);
    }

    public boolean isPlatedState() {
        return this == PLATED_SLICE
                || this == PLATED_SOUP_MEAL
                || this == PLATED_DUMPLING_MEAL
                || this == PLATED_FRIED_MEAL
                || this == PLATED_ROAST_MEAL
                || this == PLATED;
    }

    public boolean isSpoiledState() {
        return this == SPOILED || this == MOLDY;
    }

    @Override
    public String getSerializedName() {
        return this.serializedName;
    }
}
